### ISSUE TITLE
Error: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by fredmorais** [adamoutler/pikvm-homeassistant-integration#11]
Hey there! I tried to setup this integration with my PiKVM and I get the error below. I tripled checked everything, credentials, ip, etc. Thanks for the help!

```
Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pikvm_ha/config_flow.py", line 224, in async_step_user
    entry, setup_errors = await perform_device_setup(self, user_input)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/pikvm_ha/config_flow.py", line 97, in perform_device_setup
    user_input[CONF_MODEL] = response.model.lower()
                             ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by SlowCar999** [comment]
Have you ever solved the issue? I'm seeing exactly the same error.

**Comment by SlowCar999** [comment]
I managed to add my BliKVM 4 flashed with PiKVM OS by bypassing "model" by removing all "model" reference in const.py, cert_handler.py and config_flow.py.

cert_handler.py
`"""Handle certificate-related operations for PiKVM integration.
The PiKVM uses non-standard certificates, so we need to handle them manually.
Some of the expected certificatet types are:
- Non-TLSV3 compliant self-signed certificates by default.
- TLSV3 self-signed certificates
- TLSV3 certificates signed by self-signed CA
- TLSV3 certificates signed by a CA
The workarounds found in this cert_handler.py are intended to allow operation
under all circumstances assuming the PiKVM was correctly configured and not 
currently being intercepted.  The PiKVM public certificate will be recorded
during the time of the initial setup and stored in the Home Assistant configuration.
When loaded, the certificate will be used to establish a secure connection to the PiKVM.
Due to this, we are able to bypass the certificate verification process and establish
a secure connection to the PiKVM.

This module provides functions to fetch and serialize the certificate from the device. 
It also provides a function to check if the device is a PiKVM and return its serial number.
"""

from collections import namedtuple
import functools
import logging
import os
import socket
import ssl
import tempfile
import warnings

import OpenSSL
import requests
from requests.adapters import HTTPAdapter
from requests.auth import HTTPBasicAuth
from urllib3.exceptions import InsecureRequestWarning

from homeassistant.core import HomeAssistant

from .const import CONF_HOST, CONF_SERIAL

warnings.simplefilter("ignore", InsecureRequestWarning)

_LOGGER = logging.getLogger(__name__)


class SSLContextAdapter(HTTPAdapter):
    """An HTTP adapter that uses a custom SSL context."""

    def __init__(self, ssl_context, *args, **kwargs) -> None:
        """Initialize the adapter with the custom SSL context. This method is called by the session."""
        self.ssl_context = ssl_context
        super().__init__(*args, **kwargs)

    def init_poolmanager(self, *args, **kwargs) -> None:
        """Initialize the pool manager with the custom SSL context. This method is called by the session."""
        kwargs["ssl_context"] = self.ssl_context
        super().init_poolmanager(*args, **kwargs)

    def cert_verify(self, conn, *args, **kwargs) -> None:
        """Disable certificate verification. This method is called by the pool manager."""
        conn.assert_hostname = False
        conn.cert_reqs = ssl.CERT_NONE


async def create_session_with_cert(hass: HomeAssistant | None, serialized_cert=None):
    cert_file_path = None
    try:
        session = requests.Session()

        # Create an SSL context that disables all verifications
        context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
        context.check_hostname = False  # Disable hostname verification
        context.verify_mode = ssl.CERT_NONE  # Disable certificate verification

        if serialized_cert:
            with tempfile.NamedTemporaryFile(delete=False, suffix=".pem") as cert_file:
                cert_file.write(serialized_cert.encode("utf-8"))
                cert_file_path = cert_file.name
            if hass is not None:
                await hass.async_add_executor_job(
                    context.load_verify_locations, cert_file_path
                )
            else:
                context.load_verify_locations(cert_file_path)

        adapter = SSLContextAdapter(context)
        session.mount("https://", adapter)

        _LOGGER.debug("Created session with custom SSL context using the certificate")
        return session, cert_file_path if serialized_cert else None
    except Exception as e:
        _LOGGER.error("Error creating session with certificate: %s", e)
        return None, None


async def fetch_serialized_cert(hass: HomeAssistant, url: str) -> str:
    """Fetch and serialize the certificate."""
    return await hass.async_add_executor_job(_fetch_and_serialize_cert, url)


def _fetch_and_serialize_cert(url):
    """Fetch the certificate from the given URL and serializes it.

    Args:
        url (str): The URL from which to fetch the certificate.

    Returns:
        str: The serialized certificate in PEM format, or None if an error occurred.

    Raises:
        Exception: If there was an error fetching or serializing the certificate.

    """
    try:
        hostname = url.replace("https://", "").replace("http://", "").split("/")[0]
        port = 443

        context = ssl.create_default_context()
        context.check_hostname = False
        context.verify_mode = ssl.CERT_NONE

        conn = context.wrap_socket(
            socket.socket(socket.AF_INET), server_hostname=hostname
        )
        conn.connect((hostname, port))

        # Get the certificate
        cert = conn.getpeercert(True)
        x509 = OpenSSL.crypto.load_certificate(OpenSSL.crypto.FILETYPE_ASN1, cert)

        # Serialize the certificate
        serialized_cert = OpenSSL.crypto.dump_certificate(
            OpenSSL.crypto.FILETYPE_PEM, x509
        ).decode("utf-8")
        conn.close()
        return serialized_cert  # noqa: TRY300

    except (OSError, ssl.SSLError, OpenSSL.crypto.Error) as e:
        _LOGGER.error("Error fetching or serializing certificate from %s: %s", url, e)
        if "conn" in locals() and conn:
            conn.close()
        return None


def format_url(input_url):
    """Ensure the URL is properly formatted."""
    if not input_url.startswith("http"):
        input_url = f"https://{input_url}"
    return input_url.rstrip("/")


PiKVMResponse = namedtuple(
    "PiKVMResponse", ["success", "serial", "name", "error"]
)


async def is_pikvm_device(
    hass: HomeAssistant | None, url: str, username: str, password: str, cert: str
) -> tuple:
    """Check if the device is a PiKVM and return its serial number.

    Args:
      hass: HomeAssistant instance.
      url: The URL of the device.
      username: The username for the device.
      password: The password for the device.
      cert: The certificate for the device.

    Returns:
    - A tuple containing the success status, model, serial number, name, and error
    code if an error occurred. The error code may contain an HTTP status code.

    """
    url = format_url(url)
    _LOGGER.debug("Checking PiKVM device at %s with username %s", url, username)

    try:
        if hass is not None:
            session, cert_file_path = await create_session_with_cert(hass, cert)
        else:
            session, cert_file_path = await create_session_with_cert(None, cert)
        if not session:
            _LOGGER.error("Failed to create session")
            return PiKVMResponse(False, None, None, None, "HomeAssistantNoneError")

        if hass is not None:
            response = await hass.async_add_executor_job(
                functools.partial(
                    session.get,
                    f"{url}/api/info",
                    auth=HTTPBasicAuth(username, password),
                )
            )
        else:
            response = session.get(
                f"{url}/api/info", auth=HTTPBasicAuth(username, password)
            )

        _LOGGER.debug("Received response status code: %s", response.status_code)
        response.raise_for_status()

        data = response.json()
        _LOGGER.debug("Parsed response JSON: %s", data)

        if data.get("ok", False):
            result = data.get("result", {})
            hw = result.get("hw", {})
            platform = hw.get("platform", {})
            meta = result.get("meta", {})
            server = meta.get("server", {})

            serial = platform.get(CONF_SERIAL, None).lower()
            #model = platform.get(CONF_MODEL, None)
            name = server.get(CONF_HOST, None)

            _LOGGER.debug("Extracted serial number: %s", serial)
            return PiKVMResponse(True, serial, name, None)

        _LOGGER.error("Device check failed: 'ok' key not present or false")
        return PiKVMResponse(False, None, None, None, "GenericException")

    except requests.exceptions.RequestException as err:
        # Handle HTTP errors by returning a code which contains the status code
        _LOGGER.error("RequestException checking PiKVM device at %s: %s", url, err)
        error_code = (
            f"Exception_HTTP{err.response.status_code}"
            if err.response
            else "Exception_HTTP"
        )
        return PiKVMResponse(False, None, None, None, error_code)

    except ValueError as err:
        _LOGGER.error("ValueError while parsing response JSON from %s: %s", url, err)
        return PiKVMResponse(False, None, None, None, "Exception_JSON")

    finally:
        if cert_file_path and os.path.exists(cert_file_path):
            try:
                os.remove(cert_file_path)
                _LOGGER.debug("Temporary certificate file removed: %s", cert_file_path)
            except OSError as e:
                _LOGGER.warning("Failed to remove temporary certificate file: %s", e)
`

const.py
`"""Constants for the PiKVM integration."""

DOMAIN = "pikvm_ha"
#CONF_MODEL = "model"
CONF_HOST = "url"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_CERTIFICATE = "tls-certificate"
CONF_SERIAL = "serial"
DEFAULT_USERNAME = "admin"
DEFAULT_PASSWORD = "admin"
MANUFACTURER = "PiKVM"
`

config_flow.py
`"""Config flow for PiKVM integration."""

import logging
import re

from homeassistant import config_entries
from homeassistant.components.zeroconf import ZeroconfServiceInfo
from homeassistant.core import callback

from .cert_handler import fetch_serialized_cert, is_pikvm_device
from .const import (
    CONF_CERTIFICATE,
    CONF_HOST,
    #CONF_MODEL,
    CONF_PASSWORD,
    CONF_SERIAL,
    CONF_USERNAME,
    DEFAULT_PASSWORD,
    DEFAULT_USERNAME,
    DOMAIN,
    MANUFACTURER,
)
from .options_flow import PiKVMOptionsFlowHandler
from .utils import (
    create_data_schema,
    find_existing_entry,
    get_translations,
    update_existing_entry,
)

_LOGGER = logging.getLogger(__name__)


async def perform_device_setup(flow_handler, user_input):
    """Handle initial configuration setup for the configuration."""
    errors = {}
    host = user_input[CONF_HOST]
    username = user_input[CONF_USERNAME]
    password = user_input[CONF_PASSWORD]

    _LOGGER.debug(
        "Entered perform_device_setup with URL %s, username %s", host, username
    )

    try:
        # Fetch the certificate
        serialized_cert = await fetch_serialized_cert(flow_handler.hass, host)
        if not serialized_cert:
            errors["base"] = "cannot_fetch_cert"
            return None, errors

        # Store the certificate
        user_input[CONF_CERTIFICATE] = serialized_cert

        # Connect and obtain unique data from the device
        response = await is_pikvm_device(
            flow_handler.hass, host, username, password, serialized_cert
        )

        if response.error:
            errors["base"] = response.error
            return None, errors

        if not response.success:
            _LOGGER.error(
                "Error detected while connecting to PiKVM device. Error: %s",
                response.error,
            )
            # Handle the error based on response.name_or_error
            errors["base"] = "cannot_connect"
            return None, errors

        _LOGGER.debug(
            "PiKVM device detected: Serial=%s, Name=%s",
            response.serial,
            response.name,
        )

        # If an HTTP/other error occurred, then we receive a special message in the name.
        # If the user has named the device we will use it, otherwise the default will be "pikvm"
        if response.name == "localhost.localdomain":
            response.name = MANUFACTURER

        # Check if the device is already configured now that we obtained serial number
        existing_entry = find_existing_entry(flow_handler, response.serial)
        if existing_entry:
            update_existing_entry(
                flow_handler.hass,
                existing_entry,
                {CONF_HOST: host, CONF_USERNAME: username, CONF_PASSWORD: password},
            )
            return flow_handler.async_abort(reason="already_configured"), None

        # Set the unique ID based on the serial number
        user_input[CONF_SERIAL] = response.serial
        #user_input[CONF_MODEL] = response.model.lower()
        await flow_handler.async_set_unique_id(response.serial)

        # Finish config
        config_flow_result = flow_handler.async_create_entry(
            title=response.name if response.name else "PiKVM", data=user_input
        )
        return config_flow_result, None  # noqa: TRY300

    except (ConnectionError, TimeoutError, ValueError) as e:
        _LOGGER.error("Unexpected error during device setup: %s", e)
        errors["base"] = "unknown_error"

    return None, errors


class PiKVMConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
    """Handle a config flow for PiKVM."""

    VERSION = 1
    CONNECTION_CLASS = config_entries.CONN_CLASS_LOCAL_POLL

    def __init__(self) -> None:
        """Initialize the PiKVMConfigFlow."""
        self._errors: dict[str, str] = {}
        self.translations = None
        self._discovery_info: dict[str, str] = {}

    async def async_step_import(
        self, user_input=None
    ) -> config_entries.ConfigFlowResult:
        """Handle import."""
        return await self.async_step_user(user_input=user_input)

    # lets filter out the zeroconf discovery of ipv6 addresses
    async def async_step_zeroconf(self, discovery_info: ZeroconfServiceInfo) -> config_entries.ConfigFlowResult:
        """Handle the ZeroConf discovery step."""
        serial = discovery_info.properties.get("serial").lower()
        host = discovery_info.host
        if not serial or not host:
            _LOGGER.debug("Discovered device with ZeroConf but missing serial or host")
            return self.async_abort(reason="missing_serial_or_host")
        # Filter out IPv6 addresses
        if host.find(":") != -1:
            _LOGGER.debug("Discovered device with ZeroConf but IPv6 address")
            return self.async_abort(reason="ipv6_address")
        _LOGGER.debug(
            "Discovered device with ZeroConf: host=%s, serial=%s",
            host,
            serial,
        )
        existing_entry = find_existing_entry(self, serial)
        if existing_entry:
            _LOGGER.debug(
                "Device with serial %s already configured, updating existing entry",
                serial,
            )
            existing_username = existing_entry.data.get(CONF_USERNAME, DEFAULT_USERNAME)
            existing_password = existing_entry.data.get(CONF_PASSWORD, DEFAULT_PASSWORD)
            _LOGGER.debug(
                "Updating existing entry with host=%s, username=%s, password=%s",
                host,
                existing_username,
                re.sub(r'.', '*', existing_password),
            )
            update_existing_entry(
                self.hass,
                existing_entry,
                {
                    CONF_HOST: host,
                    CONF_USERNAME: existing_username,
                    CONF_PASSWORD: existing_password,
                    "serial": serial,  # Ensure serial is included
                },
            )
            return self.async_abort(reason="already_configured")
        # Offer options to add or ignore
        self._discovery_info = {
            CONF_HOST: host,
            CONF_USERNAME: DEFAULT_USERNAME,
            CONF_PASSWORD: DEFAULT_PASSWORD,
            "serial": serial,
        }
        return await self._show_zeroconf_menu()

    async def _show_zeroconf_menu(self):
        """Show menu for ZeroConf discovered device."""
        return self.async_show_menu(
            step_id="zeroconf_confirm", menu_options=["add_device", "ignore"]
        )

    async def async_step_zeroconf_confirm(
        self, user_input
    ) -> config_entries.ConfigFlowResult:
        """Handle confirmation to add or ignore the ZeroConf device."""
        if user_input == "ignore":
            _LOGGER.debug(
                "Ignoring discovered device with serial %s",
                self._discovery_info["serial"],
            )
            return self.async_abort(reason="ignored")

        # Proceed with adding the device
        entry, errors = await perform_device_setup(self, self._discovery_info)
        if entry:
            return entry

        self._errors = errors
        return await self.async_step_user(user_input=self._discovery_info)

    async def async_step_user(self, user_input=None) -> config_entries.ConfigFlowResult:
        """Handle the initial step."""
        errors = self._errors
        self._errors = {}  # Reset errors after using them

        self.translations = (
            await get_translations(self.hass, self.hass.config.language, DOMAIN) or {}
        )

        if user_input is not None:
            _LOGGER.debug(
                "Entered async_step_user with data: host=%s, username=%s, password=%s",
                user_input[CONF_HOST],
                user_input[CONF_USERNAME],
                re.sub(r'.', '*', user_input[CONF_PASSWORD]),
            )
            entry, setup_errors = await perform_device_setup(self, user_input)
            if setup_errors:
                errors.update(setup_errors)
            if entry:
                return entry

        if user_input is None:
            _LOGGER.debug("Entered async_step_user with data: None")
            user_input = self._discovery_info or {
                CONF_HOST: "",
                CONF_USERNAME: DEFAULT_USERNAME,
                CONF_PASSWORD: DEFAULT_PASSWORD,
            }
            if self._discovery_info:
                user_input[CONF_PASSWORD] = ""

        data_schema = create_data_schema(user_input)
        return self.async_show_form(
            step_id="user",
            data_schema=data_schema,
            errors=errors,
            description_placeholders={
                "url": self.translations(
                    "step.user.data.url", "URL or IP address of the PiKVM device"
                )
                if self.translations
                else "URL or IP address of the PiKVM device",
                "username": self.translations(
                    "step.user.data.username", "Username for PiKVM"
                ),
                "password": self.translations(
                    "step.user.data.password", "Password for PiKVM"
                ),
            },
        )

    @staticmethod
    @callback
    def async_get_options_flow(
        config_entry: config_entries.ConfigEntry,
    ) -> config_entries.OptionsFlow:
        """Create the options flow."""
        return PiKVMOptionsFlowHandler(config_entry)
`
